import { Calendar, Clock, Bell, ChevronRight, AlertCircle, CheckCircle2, Plus, Zap, X } from 'lucide-react';
import { useState } from 'react';
import { RegisterOvulationModal, OvulationData } from './RegisterOvulationModal';
import { RegisterInseminationModal, InseminationData } from './RegisterInseminationModal';
import { ConfirmPregnancyModal, PregnancyData } from './ConfirmPregnancyModal';

interface ReproductionAutomationTabProps {
  onNavigateToAgenda?: () => void;
}

export function ReproductionAutomationTab({ onNavigateToAgenda }: ReproductionAutomationTabProps = {}) {
  const [showOvulationModal, setShowOvulationModal] = useState(false);
  const [showInseminationModal, setShowInseminationModal] = useState(false);
  const [showPregnancyModal, setShowPregnancyModal] = useState(false);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);
  const [newEventsCount, setNewEventsCount] = useState(0);

  // Handler para ver eventos no calendário
  const handleViewCalendar = () => {
    // Navega para a aba Agenda
    if (onNavigateToAgenda) {
      onNavigateToAgenda();
    }
  };

  // Dados mockados de eventos automáticos
  const autoEvents: AutoEvent[] = [
    {
      id: 1,
      type: 'Coleta de Embrião',
      animal: 'Estrela da Manhã',
      scheduledDate: '2024-12-18',
      scheduledTime: '09:00',
      daysUntil: 8,
      priority: 'Alta',
      autoGenerated: true,
      originEvent: 'Ovulação registrada em 10/12/2024',
      notes: 'Coleta agendada automaticamente após ovulação'
    },
    {
      id: 2,
      type: 'Aplicação P4',
      animal: 'Flor do Campo',
      scheduledDate: '2024-12-15',
      scheduledTime: '14:30',
      daysUntil: 5,
      priority: 'Alta',
      autoGenerated: true,
      originEvent: 'Gestação confirmada em 01/12/2024',
      notes: '3ª aplicação da série (de 12)'
    },
    {
      id: 3,
      type: 'Aplicação P4',
      animal: 'Lua Nova',
      scheduledDate: '2024-12-16',
      scheduledTime: '10:00',
      daysUntil: 6,
      priority: 'Alta',
      autoGenerated: true,
      originEvent: 'Gestação confirmada em 25/11/2024',
      notes: '5ª aplicação da série (de 12)'
    },
    {
      id: 4,
      type: 'Diagnóstico de Gestação',
      animal: 'Vento Sul',
      scheduledDate: '2024-12-20',
      scheduledTime: '11:00',
      daysUntil: 10,
      priority: 'Média',
      autoGenerated: false,
    },
    {
      id: 5,
      type: 'Coleta de Embrião',
      animal: 'Rainha do Mar',
      scheduledDate: '2024-12-22',
      scheduledTime: '08:30',
      daysUntil: 12,
      priority: 'Alta',
      autoGenerated: true,
      originEvent: 'Inseminação (sêmen resfriado) em 14/12/2024',
      notes: 'Coleta automática 8 dias após inseminação'
    },
  ];

  // Estatísticas
  const stats = {
    totalAutomated: autoEvents.filter(e => e.autoGenerated).length,
    highPriority: autoEvents.filter(e => e.priority === 'Alta').length,
    nextWeek: autoEvents.filter(e => e.daysUntil <= 7).length,
  };

  const getEventIcon = (type: string) => {
    switch (type) {
      case 'Ovulação':
        return <Calendar className="w-5 h-5" />;
      case 'Coleta de Embrião':
        return <Bell className="w-5 h-5" />;
      case 'Aplicação P4':
        return <AlertCircle className="w-5 h-5" />;
      case 'Diagnóstico de Gestação':
        return <CheckCircle2 className="w-5 h-5" />;
      case 'Inseminação':
        return <Plus className="w-5 h-5" />;
      default:
        return <Calendar className="w-5 h-5" />;
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'Alta':
        return 'bg-red-100 dark:bg-red-900/20 text-red-700 dark:text-red-400 border-red-200 dark:border-red-800';
      case 'Média':
        return 'bg-yellow-100 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-400 border-yellow-200 dark:border-yellow-800';
      case 'Baixa':
        return 'bg-green-100 dark:bg-green-900/20 text-green-700 dark:text-green-400 border-green-200 dark:border-green-800';
      default:
        return 'bg-gray-100 dark:bg-gray-900/20 text-gray-700 dark:text-gray-400 border-gray-200 dark:border-gray-800';
    }
  };

  const getDaysColor = (days: number) => {
    if (days <= 3) return 'text-red-600 dark:text-red-400 font-semibold';
    if (days <= 7) return 'text-orange-600 dark:text-orange-400 font-medium';
    return 'text-foreground dark:text-white';
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gray-50 dark:bg-[#1a1a1a] rounded-xl p-6 border-2 border-gray-200 dark:border-white/20">
        <div className="flex items-start justify-between mb-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Zap className="w-6 h-6 text-foreground dark:text-white" />
              <h2 className="text-2xl text-foreground dark:text-white">Sequência Automática</h2>
            </div>
            <p className="text-muted-foreground dark:text-white/70">
              Eventos de reprodução agendados automaticamente pelo sistema
            </p>
          </div>
        </div>

        {/* Estatísticas */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">
          <div className="bg-white dark:bg-white/5 backdrop-blur rounded-lg p-4 border border-gray-200 dark:border-white/20">
            <div className="flex items-center gap-2 mb-1">
              <Zap className="w-5 h-5 text-foreground dark:text-white" />
              <p className="text-sm text-muted-foreground dark:text-white/70">Automáticos</p>
            </div>
            <p className="text-3xl font-semibold text-foreground dark:text-white">{stats.totalAutomated}</p>
          </div>
          <div className="bg-white dark:bg-white/5 backdrop-blur rounded-lg p-4 border border-gray-200 dark:border-white/20">
            <div className="flex items-center gap-2 mb-1">
              <AlertCircle className="w-5 h-5 text-foreground dark:text-white" />
              <p className="text-sm text-muted-foreground dark:text-white/70">Alta Prioridade</p>
            </div>
            <p className="text-3xl font-semibold text-foreground dark:text-white">{stats.highPriority}</p>
          </div>
          <div className="bg-white dark:bg-white/5 backdrop-blur rounded-lg p-4 border border-gray-200 dark:border-white/20">
            <div className="flex items-center gap-2 mb-1">
              <Clock className="w-5 h-5 text-foreground dark:text-white" />
              <p className="text-sm text-muted-foreground dark:text-white/70">Próximos 7 dias</p>
            </div>
            <p className="text-3xl font-semibold text-foreground dark:text-white">{stats.nextWeek}</p>
          </div>
        </div>
      </div>

      {/* Ações Rápidas */}
      <div className="bg-white dark:bg-[#1a1a1a] rounded-xl border border-gray-200 dark:border-[rgba(255,255,255,0.1)] p-6">
        <h3 className="text-lg text-foreground dark:text-white mb-4">Ações Rápidas</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
          <button className="p-4 border-2 border-gray-200 dark:border-[rgba(255,255,255,0.1)] bg-gray-50 dark:bg-[#0d0d0d] rounded-lg hover:border-primary dark:hover:border-white transition-colors text-left group" onClick={() => setShowOvulationModal(true)}>
            <div className="flex items-center justify-between mb-2">
              <Calendar className="w-6 h-6 text-foreground dark:text-white" />
              <ChevronRight className="w-5 h-5 text-foreground dark:text-white group-hover:translate-x-1 transition-transform" />
            </div>
            <p className="text-foreground dark:text-white font-medium mb-1">Registrar Ovulação</p>
            <p className="text-sm text-muted-foreground dark:text-[#99a1af]">
              Agenda coleta automática em +8 dias
            </p>
          </button>

          <button className="p-4 border-2 border-gray-200 dark:border-[rgba(255,255,255,0.1)] bg-gray-50 dark:bg-[#0d0d0d] rounded-lg hover:border-primary dark:hover:border-white transition-colors text-left group" onClick={() => setShowInseminationModal(true)}>
            <div className="flex items-center justify-between mb-2">
              <Plus className="w-6 h-6 text-foreground dark:text-white" />
              <ChevronRight className="w-5 h-5 text-foreground dark:text-white group-hover:translate-x-1 transition-transform" />
            </div>
            <p className="text-foreground dark:text-white font-medium mb-1">Registrar Inseminação</p>
            <p className="text-sm text-muted-foreground dark:text-[#99a1af]">
              Agenda coleta conforme tipo de sêmen
            </p>
          </button>

          <button className="p-4 border-2 border-gray-200 dark:border-[rgba(255,255,255,0.1)] bg-gray-50 dark:bg-[#0d0d0d] rounded-lg hover:border-primary dark:hover:border-white transition-colors text-left group" onClick={() => setShowPregnancyModal(true)}>
            <div className="flex items-center justify-between mb-2">
              <CheckCircle2 className="w-6 h-6 text-foreground dark:text-white" />
              <ChevronRight className="w-5 h-5 text-foreground dark:text-white group-hover:translate-x-1 transition-transform" />
            </div>
            <p className="text-foreground dark:text-white font-medium mb-1">Confirmar Gestação</p>
            <p className="text-sm text-muted-foreground dark:text-[#99a1af]">
              Cria série de P4 até dia 120
            </p>
          </button>
        </div>
      </div>

      {/* Lista de Eventos Próximos */}
      <div className="bg-white dark:bg-[#1a1a1a] rounded-xl border border-gray-200 dark:border-[rgba(255,255,255,0.1)] p-6">
        <div className="flex flex-col gap-4 mb-6">
          <div>
            <h3 className="text-lg text-foreground dark:text-white mb-1">Próximos Eventos Automáticos</h3>
            <p className="text-sm text-muted-foreground dark:text-[#99a1af]">
              {autoEvents.length} eventos agendados nos próximos 30 dias
            </p>
          </div>
          <button className="w-full sm:w-auto px-4 py-2 bg-primary dark:bg-white text-white dark:text-black rounded-lg hover:opacity-90 transition-opacity flex items-center justify-center gap-2" onClick={handleViewCalendar}>
            <Calendar className="w-4 h-4" />
            Ver no Calendário
          </button>
        </div>

        <div className="space-y-3">
          {autoEvents.map(event => {
            const [year, month, day] = event.scheduledDate.split('-');
            const formattedDate = `${day}/${month}/${year}`;

            return (
              <div
                key={event.id}
                className="border border-gray-200 dark:border-[rgba(255,255,255,0.1)] rounded-lg p-4 hover:border-primary dark:hover:border-white/40 transition-all group"
              >
                <div className="flex flex-col sm:flex-row items-start gap-4">
                  <div className="flex-1 w-full">
                    <div className="flex items-start gap-3 mb-3">
                      <div className="w-10 h-10 bg-gray-100 dark:bg-[#2a2a2a] rounded-full flex items-center justify-center flex-shrink-0 text-foreground dark:text-white">
                        {getEventIcon(event.type)}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap mb-1">
                          <h4 className="text-foreground dark:text-white font-medium">
                            {event.type}
                          </h4>
                          {event.autoGenerated && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-gray-100 dark:bg-[#2a2a2a] text-foreground dark:text-white rounded text-xs border border-gray-300 dark:border-[rgba(255,255,255,0.1)]">
                              <Zap className="w-3 h-3" />
                              Automático
                            </span>
                          )}
                          <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs border ${getPriorityColor(event.priority)}`}>
                            {event.priority}
                          </span>
                        </div>
                        <p className="text-sm text-foreground dark:text-white mb-1">
                          Animal: <span className="font-medium">{event.animal}</span>
                        </p>
                        {event.originEvent && (
                          <p className="text-xs text-muted-foreground dark:text-[#99a1af] mb-2">
                            ↳ {event.originEvent}
                          </p>
                        )}
                        {event.notes && (
                          <p className="text-xs text-muted-foreground dark:text-[#99a1af]">
                            {event.notes}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>

                  <div className="w-full sm:w-auto sm:text-right flex sm:flex-col gap-2 sm:gap-0 flex-wrap sm:flex-nowrap sm:ml-4">
                    <div className="flex items-center gap-2 sm:mb-2">
                      <Calendar className="w-4 h-4 text-muted-foreground dark:text-[#99a1af]" />
                      <span className="text-sm text-foreground dark:text-white font-medium">
                        {formattedDate}
                      </span>
                    </div>
                    <div className="flex items-center gap-2 sm:mb-2">
                      <Clock className="w-4 h-4 text-muted-foreground dark:text-[#99a1af]" />
                      <span className="text-sm text-muted-foreground dark:text-[#99a1af]">
                        {event.scheduledTime}
                      </span>
                    </div>
                    <div className={`text-sm ${getDaysColor(event.daysUntil)}`}>
                      Em {event.daysUntil} {event.daysUntil === 1 ? 'dia' : 'dias'}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>

        {autoEvents.length === 0 && (
          <div className="text-center py-12">
            <CheckCircle2 className="w-12 h-12 text-muted-foreground dark:text-[#99a1af] mx-auto mb-4" />
            <p className="text-foreground dark:text-white mb-2">Nenhum evento automático agendado</p>
            <p className="text-sm text-muted-foreground dark:text-[#99a1af]">
              Use as ações rápidas acima para criar novos eventos
            </p>
          </div>
        )}
      </div>

      {/* Modais */}
      {showOvulationModal && (
        <RegisterOvulationModal
          animalName="Estrela da Manhã"
          onClose={() => setShowOvulationModal(false)}
          onRegister={(data: OvulationData) => {
            setSuccessMessage(`Ovulação registrada! Coleta automática agendada para ${data.collectionDate}`);
            setNewEventsCount(1);
            setShowOvulationModal(false);
            setTimeout(() => setSuccessMessage(null), 5000);
          }}
        />
      )}
      
      {showInseminationModal && (
        <RegisterInseminationModal
          animalName="Estrela da Manhã"
          onClose={() => setShowInseminationModal(false)}
          onRegister={(data: InseminationData) => {
            setSuccessMessage(`Inseminação registrada! Coleta automática agendada para ${data.collectionDate}`);
            setNewEventsCount(1);
            setShowInseminationModal(false);
            setTimeout(() => setSuccessMessage(null), 5000);
          }}
        />
      )}
      
      {showPregnancyModal && (
        <ConfirmPregnancyModal
          animalName="Estrela da Manhã"
          onClose={() => setShowPregnancyModal(false)}
          onConfirm={(data: PregnancyData) => {
            const eventsCount = data.p4Schedule?.length || 0;
            setSuccessMessage(`Gestação confirmada! ${eventsCount} aplicações P4 agendadas automaticamente.`);
            setNewEventsCount(eventsCount);
            setShowPregnancyModal(false);
            setTimeout(() => setSuccessMessage(null), 5000);
          }}
        />
      )}

      {/* Mensagem de Sucesso */}
      {successMessage && (
        <div className="fixed bottom-6 right-6 bg-green-100 dark:bg-green-900/30 border-2 border-green-500 dark:border-green-600 text-green-800 dark:text-green-300 rounded-xl p-4 shadow-2xl max-w-md z-50 animate-slide-up">
          <div className="flex items-start gap-3">
            <div className="w-8 h-8 bg-green-600 dark:bg-green-500 rounded-full flex items-center justify-center flex-shrink-0">
              <CheckCircle2 className="w-5 h-5 text-white" />
            </div>
            <div className="flex-1">
              <p className="font-medium mb-1">{successMessage}</p>
              {newEventsCount > 0 && (
                <p className="text-sm text-green-700 dark:text-green-400">
                  {newEventsCount} {newEventsCount === 1 ? 'novo evento agendado' : 'novos eventos agendados'}
                </p>
              )}
            </div>
            <button
              onClick={() => setSuccessMessage(null)}
              className="p-1 hover:bg-green-200 dark:hover:bg-green-800 rounded transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}